<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tensorrt_engine</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="77548552+devonsuper@users.noreply.github.com">arpl</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!--build_depend>neuromesh_platform_r2</build_depend-->
  <!--exec_depend>neuromesh_platform_r2</exec_depend-->
  <build_depend>rclcpp_components</build_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <build_depend>tensorrt</build_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <rclcpp_components plugin="tensorrt_engine">
      <class type="tensorrt_engine_node::TensorRTEngineNode" base_class_type="rclcpp::Node">
        <description>TensorRT Engine Node</description>
      </class>
    </rclcpp_components>
  </export>
</package>
